
import { Doctor } from './types';

export const doctors: Doctor[] = [
    {
        id: 1,
        name: 'Dr. Sarah Weber',
        specialty: 'Cardiology',
        locationName: 'Charité Berlin',
        distance: 2.4,
        rating: 4.9,
        reviews: 124,
        match: 98,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAlDzkgrnplNz-1gBxw6oGBQXCF8tO3YmfQ-MuPqrZ_35wTJl1n1ngm0JKCieE7ieRmxCWUpWNtdPOke8IdbHzm0FMeB8JdyaIcuEFJPyJighMXeQHnB3k9oQMhbGt90aBBGqYcgnrRcOdtpv3gigyDKXhKZIQMmOb-NzlfusyvRchWaFVprmx2yUudvrdNPPcbfLe6PfjeuODS07qHy7QDI0hXbz58gqbgYszb5kJA5P8SYE_mv0K8WoAvjPt5PlvP2u-jHcB493w",
        isCovered: true,
        hasFastBooking: true,
        nextAvailable: 'Tomorrow, 10:00 AM',
        nextAvailableShort: 'Tomorrow, 10:00 AM',
    },
    {
        id: 2,
        name: 'Dr. Felix Müller',
        specialty: 'Cardiology',
        locationName: 'Heart Center',
        distance: 4.1,
        rating: 4.8,
        reviews: 98,
        match: 94,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTawJI2gixtqkFwV2NUUsTFov5ylbc87zKcUmE6IaCkCocpwUsrRRDKsI7JQeYeHdIJTZQQj9ARBN73Gsyue-onnoKpsoU3KdsdCyaTReCIEtp2Q36CfBQjM4EHfIcI2ogk6QfprOx2GDaES5qFQj24_J_0169Ex14aaREWPMksV887Yp4SmoDrGAjn4paw0kiFIQpJKZde_qt7tDD35XhOfM33eG8ef_ntOlbWl1Xi0wOZNSAbE711P52ppMtQb0XhBHkEFtKHDQ',
        isCovered: true,
        hasFastBooking: false,
        nextAvailable: 'Wed, 2:00 PM',
        nextAvailableShort: 'Wed, 2:00 PM',
    },
    {
        id: 3,
        name: 'Dr. Anika Klein',
        specialty: 'Internal Medicine',
        locationName: 'Private',
        distance: 1.2,
        rating: 4.7,
        reviews: 76,
        match: 89,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA-YvUxAPAlHkVDGisKHYTsk5HqaCKjzvwoxopbtLTiLA-GUqBn4xJkBQNhQMkacrei-7GeGIukUM564OOYlew7WXIehoT6lghesfuphfEY2U_zc9AtbLmYTRbK3QWs57F3R3YmwEeSx280Y7-Nh5yDSwPj3a_TYxVoM7VYe93J7Rjqg_4RyaRrIbCtCmO4ypQu-dI_Qbm_vOnqFpOxg8jFZcErAH2-C_Sd-FoDakD6_QX6JCYE3WA9xWyaGnrbUgN9GMwJqlM48Bw',
        isCovered: false,
        isOutOfNetwork: true,
        hasFastBooking: false,
        nextAvailable: 'Today, 4:30 PM',
        nextAvailableShort: 'Today, 4:30 PM',
    }
];
